Student_Project/student/student/urls.py
from django.contrib import admin
from django.urls import path,include
from studentdetail import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', views.student_post),
    path('show/', views.show),
    path('edit/<int:student_id>', views.edit),
    path('update/<int:student_id>', views.update),
    path('delete/<int:student_id>', views.delete),
]

Student_Project/student/studentdetail/models.py
from django.db import models

class Student(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20,null=True,blank=True)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    date_of_birth = models.DateField()
    roll_no = models.IntegerField()
    father_name = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    class_teacher = models.CharField(max_length=50)
        

Student_Project/student/studentdetail/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

Student_Project/student/studentdetail/views.py
from django.shortcuts import render, redirect

from .forms import StudentForm
from .models import Student

def student_post(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = StudentForm()
    return render(request,'index.html',{'form':form})

def show(request):
    students = Student.objects.all()
    return render(request,'show.html',{'students':students})

def edit(request, student_id):
    student = Student.objects.get(id=student_id)
    return render(request,'edit.html',{'student':student})

def update(request, student_id):
    student = Student.objects.get(id=student_id)
    form = StudentForm(request.POST,instance=student)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request,'edit.html',{'student':student})

def delete(request, student_id):
    student = Student.objects.get(id=student_id)
    student.delete()
    return redirect("/show")

    

Student_Project/student/studentdetail/templates/edit.html
    {% load staticfiles %}  
<form method="POST" action="/update/{{student.id}}">  
        {% csrf_token %}  
    <h3>Update Details</h3>  
    <label >Student First Name:</label>
        <input type="text" name="first_name" id="id_first_name" required maxlength="20" value="{{ student.first_name }}"/>  
    <label >Student Middle Name:</label>  
        <input type="text" name="middle_name" id="id_middle_name" required maxlength="100" value="{{ student.middle_name }}" />  
    <label >Student Last Name:</label>  
        <input type="text" name="last_name" id="id_last_name" required maxlength="254" value="{{ student.last_name }}" />  
    <label >Student Gender:</label>  
        <input type="text" name="gender" id="id_gender" required maxlength="15" value="{{ student.gender }}" />  
    <label >Student Date of Birth:</label>  
        <input type="text" name="gender" id="id_date_of_birth" required maxlength="15" value="{{ student.date_of_birth }}" />  
    <label >Student Roll No:</label>  
        <input type="text" name="gender" id="id_roll_no" required maxlength="10" value="{{ student.roll_no }}" />  
    <label >Student Father Name:</label>  
        <input type="text" name="gender" id="id_father_name" required maxlength="100" value="{{ student.father_name }}" />  
    <label >Student Mother Name:</label>  
        <input type="text" name="gender" id="id_mother_name" required maxlength="100" value="{{ student.mother_name }}" />  
    <label >Student Address:</label>  
        <input type="text" name="gender" id="id_address" required maxlength="100" value="{{ student.address }}" />  
    <label >Student Class Teacher:</label>  
        <input type="text" name="gender" id="id_class_teacher" required maxlength="100" value="{{ student.class_teacher }}" />  

    <button >Update</button>  
</form>  

Student_Project/student/studentdetail/templates/index.html
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>

Student_Project/student/studentdetail/templates/show.html
     {% load staticfiles %}  
{% for student in students %}  
        {{ student.first_name }} 
        {{ student.middle_name }}  
        {{ student.last_name }}  
        {{ student.gender }}
        {{ student.date_of_birth }}
        {{ student.roll_no }}
        {{ student.father_name }}
        {{ student.mother_name }}
        {{ student.address }}
        {{ student.class_teacher }}  
        <td>  
            <a href="/edit/{{ student.id }}"><span >Edit</span></a>  
            <a href="/delete/{{ student.id }}">Delete</a>  
        </td>  
{% endfor %}  
<center><a href="/students" >Add New Record</a></center>  